# Generated by Django 5.2.10 on 2026-01-20 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day_number'],
                'unique_together': {('user', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_goal', models.TextField(help_text="User's original goal input")),
                ('why_response_1', models.TextField(blank=True, null=True)),
                ('why_response_2', models.TextField(blank=True, null=True)),
                ('why_response_3', models.TextField(blank=True, null=True)),
                ('transformed_goal', models.TextField(blank=True, help_text='AI-enhanced powerful goal', null=True)),
                ('deep_motivation', models.TextField(blank=True, help_text='Discovered deep motivation', null=True)),
                ('baseline_value', models.IntegerField(default=0, help_text="User's current baseline")),
                ('baseline_unit', models.CharField(default='ครั้ง', max_length=50)),
                ('safe_target', models.IntegerField(default=0)),
                ('growth_target', models.IntegerField(default=0)),
                ('stretch_target', models.IntegerField(default=0)),
                ('selected_target', models.IntegerField(default=0)),
                ('goal_level', models.CharField(choices=[('safe', 'Safe Goal'), ('growth', 'Growth Goal'), ('stretch', 'Stretch Goal')], default='growth', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0, help_text='Current progress towards target')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('avatar', models.CharField(default='default', max_length=100)),
                ('total_goals_completed', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhyLadderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1)),
                ('ai_question_1', models.TextField(blank=True, null=True)),
                ('ai_question_2', models.TextField(blank=True, null=True)),
                ('ai_question_3', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='why_session', to='core.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_goal', 'First Goal Set'), ('streak_3', '3 Day Streak'), ('streak_7', '7 Day Streak'), ('streak_30', '30 Day Streak'), ('goals_10', '10 Goals Completed'), ('stretch_complete', 'Stretch Goal Completed')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=100)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
