# Generated by Django 5.2.10 on 2026-01-20 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryBoxReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎁', max_length=100)),
                ('reward_type', models.CharField(choices=[('points', 'Bonus Points'), ('quote', 'Inspirational Quote'), ('badge', 'Special Badge'), ('theme', 'Theme Unlock'), ('avatar', 'Avatar Item')], max_length=50)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('points_value', models.IntegerField(default=0, help_text='Points awarded if reward type is points')),
                ('quote_text', models.TextField(blank=True, help_text='Quote if reward type is quote', null=True)),
                ('drop_rate', models.FloatField(default=0.5, help_text='Probability 0.0-1.0')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemptationBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('podcast', 'ฟัง Podcast'), ('music', 'ฟังเพลง'), ('series', 'ดูซีรีส์'), ('youtube', 'ดู YouTube'), ('audiobook', 'ฟัง Audiobook'), ('other', 'อื่นๆ')], max_length=50)),
                ('activity_name', models.CharField(help_text='เช่น Podcast ชื่ออะไร', max_length=200)),
                ('activity_url', models.URLField(blank=True, help_text='Link to content (optional)', null=True)),
                ('icon', models.CharField(default='🎧', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temptation_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_duration', models.IntegerField(help_text='Target duration in minutes')),
                ('elapsed_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('content_unlocked', models.BooleanField(default=False, help_text='Whether temptation content is accessible')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='core.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
                ('temptation_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.temptationbundle')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True, help_text='Not yet viewed by user')),
                ('goal', models.ForeignKey(blank=True, help_text='Goal that triggered this reward', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.goal')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mysteryboxreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
    ]
