# Generated by Django 5.2.10 on 2026-01-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mysteryboxreward_temptationbundle_focussession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('day1', 'Day 1 - Foundation'), ('day2', 'Day 2 - Motivation'), ('day3', 'Day 3 - Advanced')], default='day1', max_length=50)),
                ('feature_name', models.CharField(help_text="เช่น Goals Aren't Chores", max_length=100)),
                ('content_html', models.TextField(help_text='HTML content of article')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='articles/')),
                ('icon', models.CharField(default='📖', max_length=100)),
                ('reading_time_minutes', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroll_percentage', models.IntegerField(default=0, help_text='0-100%')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
    ]
